& "$PSScriptRoot\..\gitmodules\mod-installer\build_all.ps1" `
  -Version "2.0.0" `
  -PreReleaseVersion "beta.1" `
  -OutputFilePrefix "HL2_Assault_Beta_8b_Final" `
  -ModName "HL2: Assault Beta 8b Final" `
  -ModFolder "hl2as" `
  -ModFilesPath "$PSScriptRoot\..\game" `
  -ModBaseFilesUrl "https://github.com/HL2-Mods-Legacy-Project/hl2-legacy-registry/releases/download/hl2-assault/hl2-assault-beta-8b-final-Original.zip" `
  -ModBaseFilesUrlHash "db0b587e51bf302b0d0b3caf01021f515802578a3c128cb15f409d30fbf871ee" `
  -ModReadmePath "readme.txt" `
  -PublishPath "$PSScriptRoot\..\artifacts\publish"
